# Generated by Django 4.2.6 on 2023-10-08 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                ("idBus", models.AutoField(primary_key=True, serialize=False)),
                ("propietario", models.CharField(max_length=30, null=True)),
                ("capacidad", models.IntegerField(null=True)),
                ("placa", models.CharField(max_length=10, null=True)),
                (
                    "tipo",
                    models.IntegerField(
                        choices=[(1, "Publico"), (2, "Escolar"), (3, "Turistico")],
                        default=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cooperativa",
            fields=[
                ("idCooperativa", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30, null=True)),
                ("direccion", models.CharField(max_length=30, null=True)),
                ("capacidad", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pasajero",
            fields=[
                ("idPasajero", models.AutoField(primary_key=True, serialize=False)),
                ("nombres", models.CharField(max_length=30, null=True)),
                ("cedula", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tarjeta",
            fields=[
                ("idTarjeta", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numTarjeta",
                    models.IntegerField(editable=False, null=True, verbose_name=2688),
                ),
                (
                    "saldoTarjeta",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Viaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "costoViaje",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                (
                    "idBus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrador.bus",
                    ),
                ),
                (
                    "idPasajero",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrador.pasajero",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pasajero",
            name="idTarjeta",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrador.tarjeta",
            ),
        ),
        migrations.AddField(
            model_name="pasajero",
            name="idUsuario",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="idCooperativa",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrador.cooperativa",
            ),
        ),
    ]
