# Generated by Django 4.2.6 on 2023-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tarjeta",
            name="numTarjeta",
            field=models.IntegerField(editable=False, null=True, verbose_name=7648),
        ),
    ]
